using AEET.Models;
using AEET.Models.DTOs;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace AEET.Code
{
    public class AssetManager
    {
        private readonly ApplicationDbContext _context;

        public AssetManager(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Inserts a new asset into the AssetMaster table, mapping fields from the DTO to match the DB schema.
        /// </summary>
        public async Task<AssetMaster> AddAsset(AssetMasterDto dto)
        {
            var asset = new AssetMaster
            {
                // // If AssetID is auto-generated by the DB, you can skip setting it here:
                // AssetID = string.IsNullOrEmpty(dto.AssetId)
                //     ? Guid.NewGuid()
                //     : Guid.Parse(dto.AssetId),

                // Basic Info
                CompanyName = dto.CompanyName,
                AssetName = dto.AssetName,
                AssetTag = dto.AssetTag,
                Model = dto.Model,
                ModelNo = dto.ModelNo,
                SerialNumber = dto.SerialNumber,

                // Foreign Key References (GUIDs from string values)
                CategoryID = string.IsNullOrEmpty(dto.CategoryID)
                    ? (Guid?)null : Guid.Parse(dto.CategoryID),
                ManufacturerID = string.IsNullOrEmpty(dto.ManufacturerID)
                    ? (Guid?)null : Guid.Parse(dto.ManufacturerID),
                SupplierID = string.IsNullOrEmpty(dto.SupplierID)
                    ? (Guid?)null : Guid.Parse(dto.SupplierID),
                DefaultLocationID = string.IsNullOrEmpty(dto.DefaultLocationID)
                    ? (Guid?)null : Guid.Parse(dto.DefaultLocationID),

                // Purchase & Warranty Info
                PurchasedDate = dto.PurchasedDate,
                Cost = dto.Cost,
                OrderNumber = dto.OrderNumber,
                Status = dto.Status,
                WarrantyPeriod = dto.WarrantyPeriod,
                WarrantyExpires = dto.WarrantyExpires,
                EOL = dto.EOL,
                CurrentValue = dto.CurrentValue,
                FullyDepreciated = false, // default value

                // Audit Fields (set by code; DB defaults can also be used)
                CreatedOn = DateTime.Now,
                CreatedBy = "system", // If your DB column is NVARCHAR, using a string is fine.
                ModifiedOn = DateTime.Now,
                ModifiedBy = "system",

                // Additional Information
                LastAudit = dto.LastAudit,
                NextAuditDate = dto.NextAuditDate,
                Notes = dto.Notes,
                Deleted = false
            };

            _context.AssetMasters.Add(asset);
            await _context.SaveChangesAsync();
            return asset;
        }
    }
}
